const admin = require("firebase-admin");
const serviceAccount = require("./config/serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

const books = [
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "A young shepherd travels from Spain to Egypt in search of treasure and discovers the meaning of life.",
    price: 350,
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&q=80",
    category: "Fiction",
    isFeatured: true,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A classic tale of racial injustice and childhood innocence in the American South.",
    price: 399,
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&q=80",
    category: "Fiction",
    isFeatured: false,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A story of wealth, love, and the American Dream set in the roaring 1920s.",
    price: 299,
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&q=80",
    category: "Fiction",
    isFeatured: false,
    isBestseller: false,
    createdAt: new Date(),
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    description: "A brief history of humankind from the Stone Age to the present day.",
    price: 499,
    coverImage: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=300&q=80",
    category: "Non-Fiction",
    isFeatured: true,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "Educated",
    author: "Tara Westover",
    description: "A memoir about a woman who grows up in a survivalist family and educates herself out of poverty.",
    price: 449,
    coverImage: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300&q=80",
    category: "Non-Fiction",
    isFeatured: false,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    description: "An exploration of the universe, black holes, and the nature of time by the legendary physicist.",
    price: 399,
    coverImage: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=300&q=80",
    category: "Science",
    isFeatured: true,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "The Gene",
    author: "Siddhartha Mukherjee",
    description: "An intimate history of the gene and its impact on human identity and future.",
    price: 550,
    coverImage: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=300&q=80",
    category: "Science",
    isFeatured: false,
    isBestseller: false,
    createdAt: new Date(),
  },
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    description: "Why did some civilizations conquer others? A fascinating account of how geography shaped history.",
    price: 475,
    coverImage: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=300&q=80",
    category: "History",
    isFeatured: false,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    description: "The powerful diary of a Jewish girl hiding from the Nazis during World War II.",
    price: 325,
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&q=80",
    category: "History",
    isFeatured: false,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "The timeless love story of Elizabeth Bennet and Mr. Darcy in Regency-era England.",
    price: 299,
    coverImage: "https://images.unsplash.com/photo-1474932430478-367dbb6832c1?w=300&q=80",
    category: "Romance",
    isFeatured: true,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "The Notebook",
    author: "Nicholas Sparks",
    description: "A timeless love story about two young people from different worlds who fall deeply in love.",
    price: 349,
    coverImage: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=300&q=80",
    category: "Romance",
    isFeatured: false,
    isBestseller: false,
    createdAt: new Date(),
  },
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    description: "A journalist and a hacker investigate a decades-old disappearance in a wealthy Swedish family.",
    price: 425,
    coverImage: "https://images.unsplash.com/photo-1587876931567-564ce588bfbd?w=300&q=80",
    category: "Mystery",
    isFeatured: true,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    description: "On their fifth wedding anniversary, Nick Dunne reports that his wife Amy has gone missing.",
    price: 399,
    coverImage: "https://images.unsplash.com/photo-1518744386442-2d48ac47a7eb?w=300&q=80",
    category: "Mystery",
    isFeatured: false,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "Bilbo Baggins embarks on an unexpected adventure with a group of dwarves and a wizard.",
    price: 450,
    coverImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&q=80",
    category: "Fantasy",
    isFeatured: true,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    description: "A young boy discovers he is a wizard and begins his magical journey at Hogwarts School.",
    price: 499,
    coverImage: "https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=300&q=80",
    category: "Fantasy",
    isFeatured: false,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    description: "The exclusive biography of Apple co-founder Steve Jobs based on over forty interviews.",
    price: 599,
    coverImage: "https://images.unsplash.com/photo-1491466424936-e304919aada7?w=300&q=80",
    category: "Biography",
    isFeatured: true,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    description: "The autobiography of Nelson Mandela, from his childhood to his presidency of South Africa.",
    price: 525,
    coverImage: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=300&q=80",
    category: "Biography",
    isFeatured: false,
    isBestseller: false,
    createdAt: new Date(),
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    description: "A proven framework for building good habits and breaking bad ones through tiny changes.",
    price: 499,
    coverImage: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=300&q=80",
    category: "Self-Help",
    isFeatured: true,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    description: "Powerful lessons in personal change through seven transformative habits.",
    price: 450,
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300&q=80",
    category: "Self-Help",
    isFeatured: false,
    isBestseller: true,
    createdAt: new Date(),
  },
  {
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    description: "A beloved classic about a caterpillar who eats through a variety of foods before becoming a butterfly.",
    price: 250,
    coverImage: "https://images.unsplash.com/photo-1512045482940-f37f5216f639?w=300&q=80",
    category: "Children",
    isFeatured: false,
    isBestseller: true,
    createdAt: new Date(),
  },
];

async function seedAllBooks() {
  try {
    console.log("🌱 Starting seed...");
    for (const book of books) {
      const docRef = await db.collection("books").add(book);
      console.log(`✅ Added: ${book.title} (${docRef.id})`);
    }
    console.log("\n🎉 All 20 books added successfully!");
  } catch (error) {
    console.error("❌ Error:", error.message);
  } finally {
    process.exit();
  }
}

seedAllBooks();